import React, { useState, useEffect } from "react";

import { Loader, FormField, Card } from "../components";
const Home = () => {
  const [Loading, setLoading] = useState(false);
  const [allPosts, setAllPosts] = useState(null);


  return (
    <section className="max-w-7xl mx-auto">
      <div>
        <h1 className="font-extrabold text-[#222328] text-[32px]">The community Showcase</h1>
        <p className="mt-2 text-[#667e75] text-[16px] max-w-[500px]">Browser through a collection of imaginative and visually stunnig images generated by EZE-AI-IMAGE </p>
      </div>
      <div className="mt-16">
<FormField />
      </div>

    </section>
  );
};

export default Home;
